---
title: "nofafsa_dialing_gr_5050_21TW3"
output: html_document
---

```{r load-libraries, include=FALSE}
# setup
library(DBI)
library(odbc)
library(tidyverse)
library(gt)
library(dplyr)
library(snhuthemes)
library(tidymodels)
library(lubridate)
library(airtabler)
library(ggtext)

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center',
  fig.width = 10,
  fig.height = 6
)
```



#database connection to 50222
```{r connection-string,include=FALSE}
#database connection
con_data_reporting <- dbConnect(odbc::odbc(), .connection_string = "Driver={SQL Server Native Client 11.0};\n                          Server=COCE-DS-LSTNR,50222;\n                          Database=Data_Reporting;\n                          trusted_connection=yes;")
```


#import data from query
```{r}
nofafsa_df <- dbGetQuery(
  conn = con_data_reporting, 
  statement = read_file(
    file = here::here("sql","no_fafsa_dialer_gr_21TW3.sql")
  )
) %>% as_tibble()
```



#database connection 50333
```{r connection-string,include=FALSE}
#database connection
con_data_reporting <- dbConnect(odbc::odbc(), .connection_string = "Driver={SQL Server Native Client 11.0};\n                          Server=COCE-LSTNR,50333;\n                          Database=AARDW;\n                          trusted_connection=yes;")
```



#importing Unify IDs from call logs if they were dialed in no fafsa dialer
```{r}
call_logs <- dbGetQuery(
  conn = con_data_reporting, 
  statement = read_file(
    file = here::here("sql","call_logs.sql")
  )
) %>% as_tibble()
```




# joining call logs to 50222 data
```{r}
nofafsa_df_calls <-
  as_tibble() %>%
  left_join(x = nofafsa_df,
          y = call_logs,
          by = c("ContactID" = "UnifySalesforceContactID")) 
#%>% 
  #filter(UnifySalesforceContactID != "Unknown")
  
```





#Aggregate test results to date
```{r}
nofafsa_results <- 
  nofafsa_df_calls %>% 
  #filter(fafsa_completed==0) %>% 
  group_by(testing_group) %>% 
  summarise(
      InPopulation = n(), 
      `FAFSA Completed` = sum(fafsa_completed),
      `FAFSA Completion Rate` = sum(fafsa_completed)/n(),
       Regs = sum(Regs),
      `Reg Rate` = sum(Regs) / n(),
      `FAFSA Complete Regs` = sum(fafsa_Regs),
      `FAFSA Complete Reg Rate of Pop` = sum(fafsa_Regs) / n(),
      `FAFSA Complete Reg Rate` = sum(fafsa_Regs) / sum(fafsa_completed),
      `Regs w/ FAFSA Rate` = sum(fafsa_completed) / sum(Regs),
      `Reg no FAFSA` = sum(no_fafsa_Regs)
      #  Starts = sum(Starts),
      #  `Start Rate` = sum(Starts) / n(),
      #  Enrolls = sum(Enrolls),
      # `Enroll Rate` = sum(Enrolls) / n(),
  ) %>% 
  #rename(`Test Group` = testing_group) %>% 
 gt() %>%
     fmt_percent(columns = vars(
      `FAFSA Completion Rate`,
      `Reg Rate`,
      #`Start Rate`,
      #`Enroll Rate`,
      `FAFSA Complete Reg Rate of Pop`,
      `FAFSA Complete Reg Rate`,
      `Regs w/ FAFSA Rate`
     ), decimals = 1) %>%
     fmt_number(columns = vars(
    InPopulation,
     `FAFSA Completed`,
    Regs,
    #Starts,
    `FAFSA Complete Regs`,
      `Reg no FAFSA`,
    #Enrolls
     ), decimals = 0) %>%
      data_color(columns = vars(`FAFSA Completion Rate`), colors = "lightblue") %>%
   tab_header(
    title = md("21TW3 No FAFSA Dialing Grad: Test vs. Control")) %>% 
    tab_source_note(
    source_note = c("Data Source:  Unify Opportunity, SSR - retrieved on 2/23/21"))
  #%>%
     #data_color(columns = vars(`Melt Rate`), colors = "lightgreen") %>%
    #tab_options(
      # column_labels.font.size = 13,
      # table.font.size = 12
    #)

  #FAFSA Complete Regs = Out of those that completed FAFSA, how many Registered
  #Regs w/ FAFSA Rate = Out of those that registered, how many completed FAFSAs

nofafsa_results
  
```



```{r}
# Overall results save
nofafsa_results %>% gtsave(filename = "nofafsa_21TW3_overall_20210223.png", path = here::here("imgs"))
```




#Aggregate test results to date
```{r}
nofafsa_reg_results <- 
  nofafsa_df_calls %>% 
  #filter(fafsa_completed==0) %>% 
  #group_by(testing_group) %>% 
  summarise(
      InPopulation = n(), 
      `Reg no FAFSA` = sum(no_fafsa_Regs),
      `Reg no FAFSA Rate` = sum(no_fafsa_Regs) / n()
  ) %>% 
  #rename(`Test Group` = testing_group) %>% 
 gt() %>%
     fmt_percent(columns = vars(
      `Reg no FAFSA Rate`
     ), decimals = 1) %>%
     fmt_number(columns = vars(
    InPopulation,
      `Reg no FAFSA`
     ), decimals = 0) %>%
      #data_color(columns = vars(`FAFSA Completion Rate`, `FAFSA Complete Reg Rate`), colors = "lightblue") %>%
   tab_header(
    title = md("Registered No FAFSA")) %>% 
    tab_source_note(
    source_note = c("Data Source:  Unify Opportunity, SSR - retrieved on 2/22/21"))
  #%>%
     #data_color(columns = vars(`Melt Rate`), colors = "lightgreen") %>%
    #tab_options(
      # column_labels.font.size = 13,
      # table.font.size = 12
    #)

  #FAFSA Complete Regs = Out of those that completed FAFSA, how many Registered
  #Regs w/ FAFSA Rate = Out of those that registered, how many completed FAFSAs

nofafsa_reg_results
  
```